# Cilium L2 Announcements & LoadBalancer IP Pools (M4 Task M4.2.3)
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: hpa-dev-lb-pool
  namespace: kube-system
spec:
  # Exposes the range allocated for local dynamic service LoadBalancers
  blocks:
    - cidr: "192.168.122.240/28"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: hpa-dev-l2-policy
  namespace: kube-system
spec:
  # Directs L2 announcements to be sent exclusively via primary node enp1s0 (M4 Task M4.2.3)
  interfaces:
    - enp1s0
  externalIPs: true
  loadBalancerIPs: true
