#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# hydrate-tofu.sh — Configure OpenTofu for offline provider mirror
#
# Configures OpenTofu to use a local filesystem mirror for provider
# binaries, enabling tofu init to work completely offline.
#
# Creates/updates ~/.tofurc to point at the seed's 2-tofu-registry/
# directory, then verifies with tofu init --no-download.
#
# Usage: ./hydrate-tofu.sh [--seed-dir <path>]
#                          [--tofu-dir <path>]
#                          [--user-config <path>]
# ---------------------------------------------------------------------------
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/preamble.sh"

# ---- Defaults -------------------------------------------------------------
SEED_DIR="/media/seed-appliance"
TOFU_DIR="${SCRIPT_DIR}/../opentofu"
TOFURC="${HOME}/.tofurc"
CONFIG_CREATED=false

# ---- CLI Overrides --------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed-dir)    SEED_DIR="$2";     shift 2 ;;
    --tofu-dir)    TOFU_DIR="$2";     shift 2 ;;
    --user-config) TOFURC="$2";       shift 2 ;;
    --help|-h)
      cat >&2 <<HELP
Usage: $(basename "$0") [options]

Configure OpenTofu for offline provider mirror.

Options:
  --seed-dir DIR       Seed directory (default: /media/seed-appliance)
  --tofu-dir DIR       OpenTofu project directory (default: ../opentofu)
  --user-config PATH   OpenTofu CLI config path (default: ~/.tofurc)
  --help, -h           Show this help message
HELP
      exit 0
      ;;
    *) die "Unknown argument: $1 (use --help for usage)" ;;
  esac
done

# ---- Preflight ------------------------------------------------------------
log "hydrate-tofu: starting"
log "  seed-dir:     ${SEED_DIR}/2-tofu-registry"
log "  tofu-dir:     ${TOFU_DIR}"
log "  config:       ${TOFURC}"

TOFU_MIRROR="${SEED_DIR}/2-tofu-registry"
[ -d "${TOFU_MIRROR}" ] || die "OpenTofu provider mirror not found at ${TOFU_MIRROR}"
command -v tofu >/dev/null 2>&1 || die "tofu not found in PATH"

# ---- Phase 1: Create/update ~/.tofurc ------------------------------------
log "Phase 1: Configuring OpenTofu filesystem mirror..."

# Read existing config (if any)
EXISTING_CONFIG=""
if [ -f "${TOFURC}" ]; then
  EXISTING_CONFIG=$(cat "${TOFURC}")
fi

# Generate the new config
NEW_CONFIG=$(cat <<CONFIG
# OpenTofu CLI configuration for offline provider mirror
# Generated by hydrate-tofu.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Source: ${TOFU_MIRROR}

provider_installation {
  filesystem_mirror {
    path    = "${TOFU_MIRROR}"
    include = ["registry.opentofu.org/*/*"]
  }
  direct {
    exclude = ["*"]
  }
}
CONFIG
)

if [ -n "${EXISTING_CONFIG}" ] && [ "${EXISTING_CONFIG}" != "${NEW_CONFIG}" ]; then
  log "  Existing ${TOFURC} differs — overwriting..."
fi

echo "${NEW_CONFIG}" > "${TOFURC}"
CONFIG_CREATED=true
log "  ${TOFURC}: WRITTEN"

# ---- Phase 2: Verify with tofu init --no-download ------------------------
log "Phase 2: Verifying offline provider mirror..."

cd "${TOFU_DIR}"
if tofu init --no-download 2>&1; then
  log "  tofu init --no-download: SUCCESS"
  log "  OpenTofu can now work fully offline"
else
  log "  (non-fatal) tofu init --no-download had issues — some providers may not be mirrored"
fi

# ---- Summary --------------------------------------------------------------
echo ""
echo "=== OpenTofu Offline Config Summary ==="
echo "  Config file:  ${TOFURC}"
echo "  Mirror path:  ${TOFU_MIRROR}"
echo "  Tofu project: ${TOFU_DIR}"
echo "  Config mode:  filesystem_mirror (offline)"
echo ""
echo "  File contents:"
echo "${NEW_CONFIG}"
echo ""
echo "  Next step: startup.sh (full pipeline in offline mode)"
echo "==========================================="

log "hydrate-tofu: completed successfully"
exit 0
