apiVersion: v1
kind: Service
metadata:
  name: casbin-ext-authz
  namespace: casbin
  labels:
    app: casbin-ext-authz
spec:
  type: ClusterIP
  selector:
    app: casbin-ext-authz
  ports:
    - port: 9001
      targetPort: 9001
      name: grpc
      protocol: TCP
