# Auto-generated by prep-cache.sh — enables offline mode
# Point Talos image source to local cache
local_image_path = "/home/cores/Documents/Projects/Study/HPA/with-gsd/.cache/talos-v1.13.5-metal-amd64.qcow2"
